g(3,2).
g(3,17).
g(4,1).
g(4,3).
g(4,5).
g(5,17).
g(5,11).
g(6,4).
g(6,10).
g(6,7).
g(7,8).
g(7,10).
g(8,9).
g(9,11).
g(9,12).
g(10,5).
g(11,15).
g(12,13).
g(13,14).
g(13,16).
g(15,13).
g(15,16).
g(16,18).
g(17,16).

node(X) :- g(X,_).
node(X) :- g(_,X).

%gagnant en un coup
gagnant_en_un_coup(S) :- g(S,X), not(g(X,_)).

%non perdant après 2 coup
nonperdant2coup(S) :- g(S,X), not(gagnant_en_un_coup(X)).

%peut gagner en 3 coup
peutgagner3coup(S) :- g(S,X), not(nonperdant2coup(X)).